In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from xgboost import XGBRegressor
import joblib

In [2]:
df = pd.read_csv("Salary Data.csv")
df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
370,35.0,Female,Bachelor's,Senior Marketing Analyst,8.0,85000.0
371,43.0,Male,Master's,Director of Operations,19.0,170000.0
372,29.0,Female,Bachelor's,Junior Project Manager,2.0,40000.0
373,34.0,Male,Bachelor's,Senior Operations Coordinator,7.0,90000.0
374,44.0,Female,PhD,Senior Business Analyst,15.0,150000.0

In [3]:
df.head
df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
370,35.0,Female,Bachelor's,Senior Marketing Analyst,8.0,85000.0
371,43.0,Male,Master's,Director of Operations,19.0,170000.0
372,29.0,Female,Bachelor's,Junior Project Manager,2.0,40000.0
373,34.0,Male,Bachelor's,Senior Operations Coordinator,7.0,90000.0
374,44.0,Female,PhD,Senior Business Analyst,15.0,150000.0

In [4]:
print(df.columns)

Index(['Age', 'Gender', 'Education Level', 'Job Title', 'Years of Experience',
       'Salary'],
      dtype='str')

In [5]:
print(df.dtypes)

Age                    float64
Gender                     str
Education Level            str
Job Title                  str
Years of Experience    float64
Salary                 float64
dtype: object

In [6]:
print(df.nunique())

Age                     31
Gender                   2
Education Level          3
Job Title              174
Years of Experience     28
Salary                  36
dtype: int64

In [7]:
df.isnull().sum()

Age                    2
Gender                 2
Education Level        2
Job Title              2
Years of Experience    2
Salary                 2
dtype: int64

In [8]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Gender"] = df["Gender"].fillna(df["Gender"].mode()[0])
df["Education Level"] = df["Education Level"].fillna(df["Education Level"].mode()[0])
df["Job Title"] = df["Job Title"].fillna(df["Job Title"].mode()[0])
df["Years of Experience"] = df["Years of Experience"].fillna(df["Years of Experience"].mean())
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

In [9]:
print(df.isnull().sum())

Age                    0
Gender                 0
Education Level        0
Job Title              0
Years of Experience    0
Salary                 0
dtype: int64

In [10]:
df.nunique()

Age                     32
Gender                   2
Education Level          3
Job Title              174
Years of Experience     29
Salary                  37
dtype: int64

In [11]:
le = LabelEncoder()
df["Gender"]= le.fit_transform(df["Gender"])
df["Job Title"]= le.fit_transform(df["Job Title"])
df

      Age  Gender Education Level  Job Title  Years of Experience    Salary
0    32.0       1      Bachelor's        159                  5.0   90000.0
1    28.0       0        Master's         17                  3.0   65000.0
2    45.0       1             PhD        130                 15.0  150000.0
3    36.0       0      Bachelor's        101                  7.0   60000.0
4    52.0       1        Master's         22                 20.0  200000.0
..    ...     ...             ...        ...                  ...       ...
370  35.0       0      Bachelor's        131                  8.0   85000.0
371  43.0       1        Master's         30                 19.0  170000.0
372  29.0       0      Bachelor's         70                  2.0   40000.0
373  34.0       1      Bachelor's        137                  7.0   90000.0
374  44.0       0             PhD        110                 15.0  150000.0

[375 rows x 6 columns]

In [12]:
df = pd.get_dummies(df, columns=["Education Level"])
df

,Age,Gender,Job Title,Years of Experience,Salary,Education Level_Bachelor's,Education Level_Master's,Education Level_PhD
0,32.0,1,159,5.0,90000.0,True,False,False
1,28.0,0,17,3.0,65000.0,False,True,False
2,45.0,1,130,15.0,150000.0,False,False,True
3,36.0,0,101,7.0,60000.0,True,False,False
4,52.0,1,22,20.0,200000.0,False,True,False
...,...,...,...,...,...,...,...,...
370,35.0,0,131,8.0,85000.0,True,False,False
371,43.0,1,30,19.0,170000.0,False,True,False
372,29.0,0,70,2.0,40000.0,True,False,False
373,34.0,1,137,7.0,90000.0,True,False,False
374,44.0,0,110,15.0,150000.0,False,False,True

In [13]:
df.head()

,Age,Gender,Job Title,Years of Experience,Salary,Education Level_Bachelor's,Education Level_Master's,Education Level_PhD
0,32.0,1,159,5.0,90000.0,True,False,False
1,28.0,0,17,3.0,65000.0,False,True,False
2,45.0,1,130,15.0,150000.0,False,False,True
3,36.0,0,101,7.0,60000.0,True,False,False
4,52.0,1,22,20.0,200000.0,False,True,False

In [14]:
df["Education Level_Bachelor's"] = df["Education Level_Bachelor's"].astype(int)
df["Education Level_Master's"] = df["Education Level_Master's"].astype(int)
df["Education Level_PhD"] = df["Education Level_PhD"].astype(int)
df

,Age,Gender,Job Title,Years of Experience,Salary,Education Level_Bachelor's,Education Level_Master's,Education Level_PhD
0,32.0,1,159,5.0,90000.0,1,0,0
1,28.0,0,17,3.0,65000.0,0,1,0
2,45.0,1,130,15.0,150000.0,0,0,1
3,36.0,0,101,7.0,60000.0,1,0,0
4,52.0,1,22,20.0,200000.0,0,1,0
...,...,...,...,...,...,...,...,...
370,35.0,0,131,8.0,85000.0,1,0,0
371,43.0,1,30,19.0,170000.0,0,1,0
372,29.0,0,70,2.0,40000.0,1,0,0
373,34.0,1,137,7.0,90000.0,1,0,0
374,44.0,0,110,15.0,150000.0,0,0,1

In [15]:
df.head()

,Age,Gender,Job Title,Years of Experience,Salary,Education Level_Bachelor's,Education Level_Master's,Education Level_PhD
0,32.0,1,159,5.0,90000.0,1,0,0
1,28.0,0,17,3.0,65000.0,0,1,0
2,45.0,1,130,15.0,150000.0,0,0,1
3,36.0,0,101,7.0,60000.0,1,0,0
4,52.0,1,22,20.0,200000.0,0,1,0

In [16]:
X= df.drop("Salary", axis=1)
y= df["Salary"]

print(X.shape)
print(y.shape)

(375, 7)
(375,)

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=43)
print(X_train.shape)
print(y_train.shape)

(300, 7)
(300,)

In [20]:
model = XGBRegressor(
    n_estimators = 100,
    learning_rate = 0.1,
    max_depth = 5,
    random_state = 43

)